# @package _group_
path: "./datasets"
name: "deeppose_paper2021_minimixamo"
batch_size: 2048
num_workers: 4
mirror: True
rotate: True
translate: False
augment_training: True
augment_validation: False
